language: php

matrix:
    include:
        - php: 5.3.3
          env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'
        - php: 5.3
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7.0
          env: CHECKS=yes
        - php: hhvm

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

install:
    - mkdir -p build/logs
    - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/xdebug.ini || return 0
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction
    - if [ "$CHECKS" = "yes" ]; then travis_retry composer require --no-interaction fabpot/php-cs-fixer:^1.11; fi;

script:
    - if [ "$CHECKS" = "yes" ]; then php vendor/bin/php-cs-fixer fix --dry-run -vv; fi;
    - if [ "$CHECKS" = "yes" ]; then php vendor/bin/phpcs --report=checkstyle --report-file=build/logs/checkstyle.xml --standard=build/config/phpcs.xml --ignore=*.html.php,*.config.php,*.twig.php src; fi;
    - if [ "$CHECKS" = "yes" ]; then php vendor/bin/phpmd src xml build/config/phpmd.xml --reportfile build/logs/pmd.xml; fi;
    - cp ~/xdebug.ini ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini || return 0
    - php vendor/bin/phpunit -c travis.phpunit.xml
    - rm ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini || return 0

after_script:
    - curl -s https://gist.github.com/satooshi/4750401/raw > travis/ColorCLI.php
    - curl -s https://gist.github.com/satooshi/4752226/raw > travis/junit.php
    - curl -s https://gist.github.com/satooshi/4958593/raw > travis/pmd.php
    - curl -s https://gist.github.com/satooshi/4958909/raw > travis/checkstyle.php
    - php travis/checkstyle.php
    - php travis/pmd.php
    - php travis/junit.php
    - php composer/bin/coveralls -v --exclude-no-stmt
